### PR TITLE
1.2.1-25

### PR DESCRIPTION
**Pull request by ZyC0R3**
Send.js has been updated to catch and show the correct errors for permission based issued.

### Tests Needed
- [x] Deny write permissions in server and test transaltion
- [x] Deny write permissions in destination channel and test transaltion
- [x] Deny write permissions in origin channel and test command
- [x] Deny DM from unknown users and test dm translations

### **Test with all level of permissions**
_General Permissions_
- [x] Enable and disabled
- [x] Manage Server
- [x] Manage Roles
- [x] Manage Channels
- [x] Manage Nicknames
- [x] Manage Webhooks
- [x] View Channels

_Text Permissions_
- [x] Send Messages
- [x] Manage Messages
- [x] Embed Links
- [x] Attach Files
- [x] Read Message History
- [x] Mention Everyone
- [x] Add reactions

Fall Back
- [x] Administrator

### Auxiliary Test Needed
_The below tests need to be performed with various pre conditions_
- [x] Non owner status (`DISCORD_BOT_OWNER_ID=[342394575683103265]`)
Expected Outcome, Command should be restricted to non dev commands
- [x] Owner status (`DISCORD_BOT_OWNER_ID=[Enter your ID]`)
Expected Outcome, Dev Commands allowed, all command headed with `Developer Identity confirmed:`
- [x] Embed On
- [x] Embed Off

_Translation Test_
- [x] Flag Translations
- [x] Chan Translations
- [x] Auto Translations

_Various Commands_
- [x] Version
- [x] Proc
- [x] Stats
- [x] Prefix
- [x] Embed

### CODE REVIEW

**Comment by JShep89** [comment]
removing the DM from unknown users permission: gave this error:
```Unhandled Rejection
Caused By:
DiscordAPIError: Missing Permissions
    at C:\Users\Jshep\OneDrive\Documents\GitHub\RitaBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\Jshep\OneDrive\Documents\GitHub\RitaBot\node_modules\snekfetch\src\index.js:215:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined

Error originated from server: Unknown```

**Comment by JShep89** [comment]
when the ritabot role has no permissions it still translates and responds to commands

**Comment by ZyC0R3** [comment]
> removing the DM from unknown users permission: gave this error:
> 
> ```
> Caused By:
> DiscordAPIError: Missing Permissions
>     at C:\Users\Jshep\OneDrive\Documents\GitHub\RitaBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
>     at C:\Users\Jshep\OneDrive\Documents\GitHub\RitaBot\node_modules\snekfetch\src\index.js:215:21
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> undefined
> 
> Error originated from server: Unknown```
> ```

Was this in Console or webhook chan.

**Comment by JShep89** [comment]
> > removing the DM from unknown users permission: gave this error:
> > ```
> > Caused By:
> > DiscordAPIError: Missing Permissions
> >     at C:\Users\Jshep\OneDrive\Documents\GitHub\RitaBot\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
> >     at C:\Users\Jshep\OneDrive\Documents\GitHub\RitaBot\node_modules\snekfetch\src\index.js:215:21
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > undefined
> > 
> > Error originated from server: Unknown```
> > ```
> 
> Was this in Console or webhook chan.

It was showing in both but now it is only showing in console

**Comment by JShep89** [comment]
list servers command didnt have the Developer Identity confirmed header

**Comment by ArtanisTheOne** [comment]
> when the ritabot role has no permissions it still translates and responds to commands

Flawed test due to `@everyone` permissions interfering with RitaBot's permissions. When the bot has no read permissions it cannot see the command & without send permissions but with read permissions it DM's server owner (perhaps change this to DM'ming the user as well as the server owner). Also, we will need to update the guide to have people enable member intents.

**Comment by JShep89** [comment]
> > when the ritabot role has no permissions it still translates and responds to commands
> 
> Flawed test due to `@everyone` permissions interfering with RitaBot's permissions. When the bot has no read permissions it cannot see the command & without send permissions but with read permissions it DM's server owner (perhaps change this to DM'ming the user as well as the server owner). Also, we will need to update the guide to have people enable member intents.

Reconducted those tests with the "@everyone" perms set properly and they worked as expected

**Comment by JShep89** [comment]
the "@everyone" mention appears to be broken, also rita doesn't react across channels. any thoughts on how to perform those test would be appreciated

**Comment by JShep89** [comment]
unsure of how to test these perms as none of them pertain to any current command or function of rita:
 Manage Server
 Manage Roles
 Manage Channels
 Manage Nicknames

**Review by JShep89 — APPROVED** [review]
after thorough testing, I conclude that there are no Breaking changes in this Patch and therefor approve it for merge

**Comment by ZyC0R3** [comment]
Hold off on merge for a moment untill eslint changes are approved.

**Review by JShep89 — APPROVED** [review]

**Comment by ZyC0R3** [comment]
Debug command has been added, and correctly ceate channel, webhook and then save values in db. 
Gif keyboard no longer gives and error when used.

**Review by ArtanisTheOne — APPROVED** [review]

**Pull request merged**
