### PR TITLE
Changed local install instructions

### PR DESCRIPTION
**Pull request by megahypercat**
I removed steps that you don't have to do, and streamlined the process.
The old ones were a bit confusing for me - Because there's actually no need to set up or configure the database. The default settings work just fine, Sqlite3 is is installed when you do npm install. There's little reason to change the directory of the database.

I think this makes it much easier to install, and to install what you actually need to do to install it.
PS. Great bot, I love it

### CODE REVIEW

**Comment by ZyC0R3** [comment]
This is really helpfull, we are always looking to streamline any steps so thank you for this.

There are some vital parts that are still needed in this setup however, the **DATABASE_URL** steps. While it is possiable for the bot to detect these and use this from the default setup, these steps should be included as a extra for advance users that want to use a diffrent DB or file location. 

I have changed the branch this PR is for to be our test branch as we only push changes to master upon new relases, so this will be bundled with next release if you are happy for that to happen.

**Comment by ZyC0R3** [comment]
i have sugested an addition to your edit. 

```md
#### Alternative Database Settings
Any Database that runs with [SQL Sequelize](https://sequelize.org/master/) can be used. If you want to use an alternative DB Location other than in the default directory then you can manually set this. Example: The connection to a sqlite database with the name *`database.db`* stored at the same level of this README file would be *`./database.db`*.

Within the **.env** file from the above step, set the **DATABASE_URL** to be the path to the database file, if there is no DB file in the selected path then RITA will create the DB file upon startup.
* Example -  `DATABASE_URL` = `C:\Admin\Rita_Development\test.db`
```

**Comment by megahypercat** [comment]
Hi, yes that sounds good. I shouldn't have just removed that, even if it shouldn't be in the "list of steps to get it running"
Thanks ( :

**Comment by ZyC0R3** [comment]
Thank you, We will incoriprate these cahgnes in the next push, Keep any recommendations coming as they can only help imporve RITA for other to use.

**Pull request closed without merging**
